/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Product;
import model.Record;
import model.ServiceRecord;

/**
 *
 * @author anvithalakshmisha
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
//    Product product;
    Record record;
//    ServiceRecord sr;
    String[] serviceRecord = new String[3];

    public CreateJPanel(Record record, ServiceRecord sr) {
        initComponents();

//        this.product = product;
        this.record = record;
//        this.sr = sr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModel = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblEngineNo = new javax.swing.JLabel();
        lblSeatsNumber = new javax.swing.JLabel();
        lblLicensePlate = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        lblTelephoneNo = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblDriverLicense = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblWarrantYear = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtEngineNo = new javax.swing.JTextField();
        txtLicensePlate = new javax.swing.JTextField();
        txtTelephoneNo = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtDriverLicense = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtSeatNos = new javax.swing.JTextField();
        txtOwnerName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaAddress = new javax.swing.JTextArea();
        txtWarrantYear = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        lblImageUploadtxt = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblLastMainDate = new javax.swing.JLabel();
        lblPreviousOwner = new javax.swing.JLabel();
        lblMainCount = new javax.swing.JLabel();
        txtLastMainDate = new javax.swing.JTextField();
        txtPreviousOwner = new javax.swing.JTextField();
        txtMainCount = new javax.swing.JTextField();
        btnAddServiceRcd = new javax.swing.JButton();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lblModel.setText("Model :");

        lblAddress.setText("Address :");

        lblColor.setText("Color :");

        lblYear.setText("Year :");

        lblEngineNo.setText("Engine number :");

        lblSeatsNumber.setText("Seats number :");

        lblLicensePlate.setText("License plate :");

        lblOwnerName.setText("Owner Name :");

        lblTelephoneNo.setText("Owner telephone number :");

        lblEmailAddress.setText("Owner email address :");

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create a car product");

        lblDriverLicense.setText("Owner driver license :");

        lblBrand.setText("Brand :");

        lblSSN.setText("Owner Social security number :");

        lblWarrantYear.setText("Warranty year :");

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        txtTelephoneNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelephoneNoFocusLost(evt);
            }
        });
        txtTelephoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNoActionPerformed(evt);
            }
        });
        txtTelephoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelephoneNoKeyPressed(evt);
            }
        });

        txtEmailAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailAddressFocusLost(evt);
            }
        });
        txtEmailAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailAddressKeyPressed(evt);
            }
        });

        txtYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtYearFocusLost(evt);
            }
        });
        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtYearKeyPressed(evt);
            }
        });

        txtSeatNos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSeatNosFocusLost(evt);
            }
        });
        txtSeatNos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatNosActionPerformed(evt);
            }
        });
        txtSeatNos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSeatNosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSeatNosKeyReleased(evt);
            }
        });

        txtAreaAddress.setColumns(20);
        txtAreaAddress.setRows(5);
        jScrollPane2.setViewportView(txtAreaAddress);

        txtWarrantYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWarrantYearFocusLost(evt);
            }
        });
        txtWarrantYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWarrantYearActionPerformed(evt);
            }
        });
        txtWarrantYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWarrantYearKeyPressed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBrowse.setText("browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        lblImageUploadtxt.setText("Upload image");

        lblTitle2.setText("Add Service record");

        lblLastMainDate.setText("Last maintenance date");

        lblPreviousOwner.setText("Previous owner details");

        lblMainCount.setText("Maintenance count till date");

        txtMainCount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMainCountKeyPressed(evt);
            }
        });

        btnAddServiceRcd.setText("Add another service record");
        btnAddServiceRcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceRcdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(174, 174, 174)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblImageUploadtxt)
                                            .addComponent(lblDriverLicense)
                                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtWarrantYear, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(lblSSN)))
                                        .addGap(31, 31, 31)
                                        .addComponent(btnBrowse))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblLastMainDate)
                                                    .addComponent(lblPreviousOwner))
                                                .addGap(52, 52, 52)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtPreviousOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtLastMainDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblMainCount)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtMainCount, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(26, 26, 26)
                                                        .addComponent(btnAddServiceRcd)))))))
                                .addGap(18, 18, 18)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblBrand)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEngineNo)
                                    .addComponent(lblModel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLicensePlate)
                                        .addGap(3, 3, 3))
                                    .addComponent(lblYear)
                                    .addComponent(lblWarrantYear)
                                    .addComponent(lblSeatsNumber))
                                .addGap(1, 1, 1)))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSeatNos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOwnerName)
                            .addComponent(lblEmailAddress)
                            .addComponent(lblTelephoneNo)
                            .addComponent(lblAddress))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDriverLicense, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(507, 507, 507))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTitle)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrand)
                    .addComponent(lblOwnerName)
                    .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailAddress)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(lblYear))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDriverLicense)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblColor)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAddress))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(lblEngineNo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSeatsNumber)
                                    .addComponent(txtSeatNos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblModel)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelephoneNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLicensePlate)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lblTitle2)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastMainDate)
                            .addComponent(txtLastMainDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPreviousOwner)
                            .addComponent(txtPreviousOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMainCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMainCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddServiceRcd)
                        .addGap(0, 110, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWarrantYear)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSSN)
                                .addComponent(txtWarrantYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImageUploadtxt)
                                    .addComponent(btnBrowse))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtSeatNosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatNosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatNosActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        String brand = txtBrand.getText();
        String model = txtModel.getText();
        String color = txtColor.getText();
        int year = Integer.parseInt(txtYear.getText());
        String engineNo = txtEngineNo.getText();
        int seatsNo = Integer.parseInt(txtSeatNos.getText());
        String LicensePlate = txtLicensePlate.getText();
        String OwnerName = txtOwnerName.getText();
        int telePhoneNo = Integer.parseInt(txtTelephoneNo.getText());
        String emailAddress = txtEmailAddress.getText();
        String driverLicense = txtDriverLicense.getText();
        String SSN = txtSSN.getText();
        String address = txtAreaAddress.getText();
        int warrantyYear = Integer.parseInt(txtWarrantYear.getText());
//        String lastMaintenanceDate = txtLastMainDate.getText();
//        String previousOwner = txtPreviousOwner.getText();
//        int mainCount = Integer.parseInt(txtMainCount.getText());
//        String[] serviceRecord = new String[3];
        serviceRecord[0] = txtLastMainDate.getText();
        serviceRecord[1] = txtPreviousOwner.getText();
        serviceRecord[2] = txtMainCount.getText();
//        Icon picString = lblImage.getIcon();
//        String lastMaintenanceDate = txtLastMainDate.getText();
//        String previousOwner = txtPreviousOwner.getText();
//        int mainCount = Integer.parseInt(txtMainCount.getText());
//if there is a single service record

//        ServiceRecord sp = sr.addNewServiceRecord();
//        sp.setLastMaintenanceDate(lastMaintenanceDate);
//        sp.setNumberOfMaintenanceHistory(mainCount);
//        sp.setPreviousOwner(previousOwner);

//        ServiceRecord serviceRecord = sp;

        Product p = record.addNewRecord();

        p.setBrand(brand);
        p.setModel(model);
        p.setColor(color);
        p.setYear(year);
        p.setEngineNo(engineNo);
        p.setSeatsNo(seatsNo);
        p.setLicensePlate(LicensePlate);
        p.setOwnerName(OwnerName);
        p.setTelephoneNo(telePhoneNo);
        p.setEmailAddress(emailAddress);
        p.setDriverLicense(driverLicense);
        p.setSsn(SSN);
        p.setAddress(address);
        p.setWarrantyYear(warrantyYear);
        p.setServiceRecords(serviceRecord);
//        p.setPic(picString);
//        p.setServiceRecords([lastMaintenanceDate, previousOwner, mainCount]);
//        p.setLastMaintenanceDate(lastMaintenanceDate);
//        p.setNumberOfMaintenanceHistory(mainCount);
//        p.setPreviousOwner(previousOwner);
        JOptionPane.showMessageDialog(this, "Car product created and saved successfully !");


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:

        JFileChooser browseImage = new JFileChooser();
//        Filter image selection
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("images", "png", "jpg", "jpeg");
        browseImage.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImage.showOpenDialog(null);
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = browseImage.getSelectedFile();
            String selectedImagePath = selectedFile.getAbsolutePath();

//            Display image
            ImageIcon ii = new ImageIcon(selectedImagePath);
//            resize the image to fit the label 
            Image image = ii.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
            lblImage.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void txtTelephoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneNoActionPerformed

    private void txtWarrantYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWarrantYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWarrantYearActionPerformed

    private void btnAddServiceRcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceRcdActionPerformed
        // TODO add your handling code here:
//        String lastMaintenanceDate = txtLastMainDate.getText();
//        String previousOwner = txtPreviousOwner.getText();
//        int mainCount = Integer.parseInt(txtMainCount.getText());
//        ServiceRecord sp = sr.addNewServiceRecord();
//        sp.setLastMaintenanceDate(lastMaintenanceDate);
//        sp.setNumberOfMaintenanceHistory(mainCount);
//        sp.setPreviousOwner(previousOwner);
//String[] serviceRecord = new String[3];
        serviceRecord[0] = txtLastMainDate.getText();
        serviceRecord[1] = txtPreviousOwner.getText();
        serviceRecord[2] = txtMainCount.getText();
        txtLastMainDate.setText("");
        txtPreviousOwner.setText("");
        txtMainCount.setText("");
    }//GEN-LAST:event_btnAddServiceRcdActionPerformed

    private void txtSeatNosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSeatNosFocusLost
        // TODO add your handling code here:
        if (!evt.isTemporary()) {
        int key = Integer.parseInt(txtSeatNos.getText());
        if (!((key >=0) || (key == KeyEvent.VK_BACK_SPACE))) {
            JOptionPane.showMessageDialog(this, "Enter only number");
        }
        }
    }//GEN-LAST:event_txtSeatNosFocusLost

    private void txtYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYearFocusLost
        // TODO add your handling code here:
        if (!evt.isTemporary()) {
          int key = Integer.parseInt(txtYear.getText());
        if (!((key >= 0) || (key == KeyEvent.VK_BACK_SPACE))) {
            JOptionPane.showMessageDialog(this, "Enter only number");
        } else {
            String year = txtYear.getText();
            int count = year.length();
            if(count != 4) {
                JOptionPane.showMessageDialog(this, "Enter valid year");
            }
        }
        }
    }//GEN-LAST:event_txtYearFocusLost

    private void txtWarrantYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWarrantYearFocusLost
        // TODO add your handling code here:
        if (!evt.isTemporary()) {
          int key = Integer.parseInt(txtWarrantYear.getText());
        if (!((key >= 0) || (key == KeyEvent.VK_BACK_SPACE))) {
            JOptionPane.showMessageDialog(this, "Enter only number");
        } else {
            String year = txtWarrantYear.getText();
            int count = year.length();
            if(count != 4) {
                JOptionPane.showMessageDialog(this, "Enter valid year");
            }
        }
        }
    }//GEN-LAST:event_txtWarrantYearFocusLost

    private void txtTelephoneNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelephoneNoFocusLost
        // TODO add your handling code here:
        if (!evt.isTemporary()) {
        int key = Integer.parseInt(txtTelephoneNo.getText());
        if (!((key >= 0) || (key == KeyEvent.VK_BACK_SPACE))) {
            JOptionPane.showMessageDialog(this, "Enter only number");
        } else {
            String tno = txtTelephoneNo.getText();
            int count = tno.length();
            if(count != 10) {
                JOptionPane.showMessageDialog(this, "Enter valid phone number");
            }
        }
        }
    }//GEN-LAST:event_txtTelephoneNoFocusLost

    private void txtEmailAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailAddressFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddressFocusLost

    private void txtSeatNosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeatNosKeyPressed
        // TODO add your handling code here:
//        int key = evt.getKeyChar();
//        if (!((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key == KeyEvent.VK_BACK_SPACE))) {
//            JOptionPane.showMessageDialog(this, "Enter only number");
//        }
    }//GEN-LAST:event_txtSeatNosKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void txtYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyPressed
        // TODO add your handling code here:
//        int key = evt.getKeyChar();
//        String year = txtYear.getText();
//        int count = year.length();
//        if (!((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key == KeyEvent.VK_BACK_SPACE))) {
//            JOptionPane.showMessageDialog(this, "Enter only number");
//        }
//        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)) {
//            if (count != 4) {
//                JOptionPane.showMessageDialog(this, "Enter valid year");
//            }
//
//        }
    }//GEN-LAST:event_txtYearKeyPressed

    private void txtWarrantYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWarrantYearKeyPressed
        // TODO add your handling code here:
//        int key = evt.getKeyChar();
//        String warrantyYear = txtWarrantYear.getText();
//        int count = warrantyYear.length();
//        if (!((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key == KeyEvent.VK_BACK_SPACE))) {
//            JOptionPane.showMessageDialog(this, "Enter only number");
//        }
//        if ((key >= evt.VK_0 && key <= evt.VK_9) || (key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)) {
//            if (count != 4) {
//                JOptionPane.showMessageDialog(this, "Enter valid year");
//            }
//
//        }
    }//GEN-LAST:event_txtWarrantYearKeyPressed

    private void txtTelephoneNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelephoneNoKeyPressed
        // TODO add your handling code here:
//        int key = evt.getKeyChar();
//        String phoneNumber = txtTelephoneNo.getText();
//        int count = phoneNumber.length();
//        if (!((key > evt.VK_0 && key <= evt.VK_9) || (key > evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key == KeyEvent.VK_BACK_SPACE))) {
//            JOptionPane.showMessageDialog(this, "Enter only number");
//        }
//        if ((key > evt.VK_0 && key <= evt.VK_9) || (key > evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9)) {
//            if (count != 10) {
//                JOptionPane.showMessageDialog(this, "Enter valid phone number");
//            }
//
//        }
    }//GEN-LAST:event_txtTelephoneNoKeyPressed

    private void txtEmailAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailAddressKeyPressed
        // TODO add your handling code here:
//        String email = txtEmailAddress.getText();
//        String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

//        if (!email.contains(EMAIL_PATTERN)) {
//            JOptionPane.showMessageDialog(this, "Enter valid email address");
//        }
    }//GEN-LAST:event_txtEmailAddressKeyPressed

    private void txtMainCountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMainCountKeyPressed
        // TODO add your handling code here:
//        int key = evt.getKeyChar();
//        if (!((key > evt.VK_0 && key <= evt.VK_9) || (key > evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key == KeyEvent.VK_BACK_SPACE))) {
//            JOptionPane.showMessageDialog(this, "Enter only number");
//        }
    }//GEN-LAST:event_txtMainCountKeyPressed

    private void txtSeatNosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeatNosKeyReleased
        // TODO add your handling code here:
//        int key = evt.getKeyChar();
//        if (!((key > evt.VK_0 && key <= evt.VK_9) || (key > evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key == KeyEvent.VK_BACK_SPACE))) {
//            JOptionPane.showMessageDialog(this, "Enter only number");
//        }
    }//GEN-LAST:event_txtSeatNosKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddServiceRcd;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblDriverLicense;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEngineNo;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblImageUploadtxt;
    private javax.swing.JLabel lblLastMainDate;
    private javax.swing.JLabel lblLicensePlate;
    private javax.swing.JLabel lblMainCount;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblPreviousOwner;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSeatsNumber;
    private javax.swing.JLabel lblTelephoneNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblWarrantYear;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextArea txtAreaAddress;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDriverLicense;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtEngineNo;
    private javax.swing.JTextField txtLastMainDate;
    private javax.swing.JTextField txtLicensePlate;
    private javax.swing.JTextField txtMainCount;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtPreviousOwner;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSeatNos;
    private javax.swing.JTextField txtTelephoneNo;
    private javax.swing.JTextField txtWarrantYear;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
