/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Product;
import model.Record;
import model.ServiceRecord;

/**
 *
 * @author anvithalakshmisha
 */
public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
//    Product product;
    Record record;
//    ServiceRecord sr;

    public DisplayJPanel(Record record, ServiceRecord sr) {
        initComponents();

//        this.product = product;
        this.record = record;
//        this.sr = sr;

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtEngineNo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaAddress = new javax.swing.JTextArea();
        lblAddress = new javax.swing.JLabel();
        txtWarrantYear = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtLicensePlate = new javax.swing.JTextField();
        txtTelephoneNo = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        lblEngineNo = new javax.swing.JLabel();
        lblSeatsNumber = new javax.swing.JLabel();
        lblLicensePlate = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        txtEmailAddress = new javax.swing.JTextField();
        lblTelephoneNo = new javax.swing.JLabel();
        txtDriverLicense = new javax.swing.JTextField();
        lblEmailAddress = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblDriverLicense = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        txtSeatNos = new javax.swing.JTextField();
        txtOwnerName = new javax.swing.JTextField();
        lblWarrantYear = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblServiceRecords = new javax.swing.JTable();
        btnViewRecord = new javax.swing.JButton();
        btnDeleteRecord = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();
        lblServiceRecord = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View car product");

        txtBrand.setEditable(false);

        txtColor.setEditable(false);
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        lblModel.setText("Model :");

        txtEngineNo.setEditable(false);

        txtAreaAddress.setEditable(false);
        txtAreaAddress.setColumns(20);
        txtAreaAddress.setRows(5);
        jScrollPane2.setViewportView(txtAreaAddress);

        lblAddress.setText("Address :");

        txtWarrantYear.setEditable(false);

        lblColor.setText("Color :");

        txtLicensePlate.setEditable(false);
        txtLicensePlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicensePlateActionPerformed(evt);
            }
        });

        txtTelephoneNo.setEditable(false);
        txtTelephoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNoActionPerformed(evt);
            }
        });

        lblYear.setText("Year :");

        lblEngineNo.setText("Engine number :");

        lblSeatsNumber.setText("Seats number :");

        lblLicensePlate.setText("License plate :");

        lblOwnerName.setText("Owner Name :");

        txtEmailAddress.setEditable(false);

        lblTelephoneNo.setText("Owner telephone number :");

        txtDriverLicense.setEditable(false);

        lblEmailAddress.setText("Owner email address :");

        txtSSN.setEditable(false);

        lblDriverLicense.setText("Owner driver license :");

        lblBrand.setText("Brand :");

        txtModel.setEditable(false);
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        lblSSN.setText("Owner Social security number :");

        txtYear.setEditable(false);

        txtSeatNos.setEditable(false);
        txtSeatNos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatNosActionPerformed(evt);
            }
        });

        lblWarrantYear.setText("Warranty year :");

        tblServiceRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Engine Number", "Warranty year", "Brand", "Model"
            }
        ));
        jScrollPane3.setViewportView(tblServiceRecords);

        btnViewRecord.setText("View record");
        btnViewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRecordActionPerformed(evt);
            }
        });

        btnDeleteRecord.setText("Delete record");
        btnDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordActionPerformed(evt);
            }
        });

        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Previous Owner", "Last maintenance date", "Number of maintenance till date"
            }
        ));
        jScrollPane1.setViewportView(tblService);

        lblServiceRecord.setText("Service record");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnViewRecord)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDeleteRecord))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblServiceRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBrand)
                                    .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEngineNo)
                                    .addComponent(lblLicensePlate)
                                    .addComponent(lblTelephoneNo)
                                    .addComponent(lblEmailAddress)
                                    .addComponent(lblDriverLicense))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(155, 155, 155)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(155, 155, 155)
                                        .addComponent(txtSeatNos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(155, 155, 155)
                                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAddress)
                                            .addComponent(lblWarrantYear)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49)
                                                .addComponent(lblOwnerName))
                                            .addComponent(lblSeatsNumber)
                                            .addComponent(lblYear)
                                            .addComponent(lblModel))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtWarrantYear, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblSSN)
                                .addGap(18, 18, 18)
                                .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteRecord)
                            .addComponent(btnViewRecord))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBrand)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModel)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblColor)
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblYear)
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEngineNo)
                                    .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSeatsNumber)
                                    .addComponent(txtSeatNos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOwnerName)
                            .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicensePlate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblEmailAddress)
                                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAddress))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDriverLicense)
                                    .addComponent(txtDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblWarrantYear)
                                            .addComponent(txtWarrantYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblSSN)
                                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblServiceRecord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtSeatNosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatNosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatNosActionPerformed

    private void txtTelephoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneNoActionPerformed

    private void btnViewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRecordActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblServiceRecords.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblServiceRecords.getModel();
        Product selectedProduct = (Product) model.getValueAt(selectedRowIndex, 0);

        displayProduct(selectedProduct);
        populateServiceRecordTable(selectedProduct);
    }//GEN-LAST:event_btnViewRecordActionPerformed

    private void btnDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblServiceRecords.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblServiceRecords.getModel();
        Product selectedProduct = (Product) model.getValueAt(selectedRowIndex, 0);

        record.deleteRecord(selectedProduct);
        JOptionPane.showMessageDialog(this, "Record deleted");

        populateTable();
        populateServiceRecordTable(selectedProduct);
        txtBrand.setText("");
        txtModel.setText("");
        txtColor.setText("");
        txtYear.setText("");
        txtEngineNo.setText("");
        txtSeatNos.setText("");
        txtLicensePlate.setText("");
        txtOwnerName.setText("");
        txtTelephoneNo.setText("");
        txtEmailAddress.setText("");
        txtDriverLicense.setText("");
        txtSSN.setText("");
        txtAreaAddress.setText("");
        txtWarrantYear.setText("");

    }//GEN-LAST:event_btnDeleteRecordActionPerformed

    private void txtLicensePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicensePlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicensePlateActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteRecord;
    private javax.swing.JButton btnViewRecord;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblDriverLicense;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEngineNo;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLicensePlate;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSeatsNumber;
    private javax.swing.JLabel lblServiceRecord;
    private javax.swing.JLabel lblTelephoneNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWarrantYear;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTable tblService;
    private javax.swing.JTable tblServiceRecords;
    private javax.swing.JTextArea txtAreaAddress;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDriverLicense;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtEngineNo;
    private javax.swing.JTextField txtLicensePlate;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSeatNos;
    private javax.swing.JTextField txtTelephoneNo;
    private javax.swing.JTextField txtWarrantYear;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    private void displayProduct(Product sp) {

        txtBrand.setText(sp.getBrand());
        txtModel.setText(sp.getModel());
        txtColor.setText(sp.getColor());
        txtYear.setText(String.valueOf(sp.getYear()));
        txtEngineNo.setText(sp.getEngineNo());
        txtSeatNos.setText(String.valueOf(sp.getSeatsNo()));
        txtLicensePlate.setText(sp.getLicensePlate());
        txtOwnerName.setText(sp.getOwnerName());
        txtTelephoneNo.setText(String.valueOf(sp.getTelephoneNo()));
        txtEmailAddress.setText(sp.getEmailAddress());
        txtDriverLicense.setText(sp.getDriverLicense());
        txtSSN.setText(sp.getSsn());
        txtAreaAddress.setText(sp.getAddress());
        txtWarrantYear.setText(String.valueOf(sp.getWarrantyYear()));
//        lblImage.setIcon(sp.getPic());
    }

//    Show all the car records
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblServiceRecords.getModel();
        model.setRowCount(0);

        for (Product p : record.getRecord()) {

            Object[] row = new Object[4];
            row[0] = p;
//            row[0] = p.getEngineNo();
            row[1] = p.getWarrantyYear();
            row[2] = p.getBrand();
            row[3] = p.getModel();

            model.addRow(row);

        }
    }

//    Show the service records of a particular car
    private void populateServiceRecordTable(Product selectedProduct) {
        DefaultTableModel model = (DefaultTableModel) tblService.getModel();
        model.setRowCount(0);
        
        model.addRow(selectedProduct.getServiceRecords());

//        if(selectedProduct) {
//        for (Product p : record.getRecord()) {
////            for (String sr: selectedProduct.getServiceRecords()) {
//
//                Object[] row = new Object[3];
////            row[0] = sr;
////                row[0] = sr.getPreviousOwner();
////                row[1] = sr.getLastMaintenanceDate();
////                row[2] = sr.getNumberOfMaintenanceHistory();
//
//                model.addRow(row);
//            }
//        }
//        }
    }

}
